=== engsulta/Chatter/Client/src/main/java/com/jdevsul/xml_schema/Message_Schema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
           <xs:element name="chatHistory" type="Messages"/>
           <xs:complexType name="Messages">
               <xs:sequence>
                   <xs:element name="From" type="xs:string"/>
                   <xs:element name="To" type="xs:string" maxOccurs="unbounded"/>
                   <xs:element name="Msg" type="MessageDetails" maxOccurs="unbounded"/>

               </xs:sequence>
           </xs:complexType>
           
           <xs:complexType name="MessageDetails">
               <xs:sequence>
                   <xs:element name="Content" type="xs:string"/>
                   <xs:element name="Date" type="xs:date"/>
                   <xs:element name="Format" type="MessageFormat"/>          
               </xs:sequence>
           </xs:complexType>
               
           <xs:complexType name="MessageFormat">
               <xs:sequence>
                   <xs:element name="Color" type="xs:string" />
                   <xs:element name="FontName" type="xs:string" />
                   <xs:element name="FontStyle" type="xs:string"/>
                   <xs:element name="FontSize" type="xs:integer"/>
                   
               </xs:sequence>
           </xs:complexType>
</xs:schema>

=== engsulta/Chatter/Client/src/main/java/com/jdevsul/xml_schema/testXml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<chatHistory  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Message_Schema.xsd">
    <From>Gehad</From>
    <To>Eman</To>
    <To>Sherif</To>
    <To>Sultan</To>
    <Msg>
        <Content>Hi, How are you?</Content>
        <Date>2018-02-09+07:00</Date>
        <Format>
            <Color>Red</Color>
            <FontName>TimesNewRoman</FontName>
            <FontSize>14</FontSize>
            <FontStyle>Bold</FontStyle>
        </Format>
    </Msg>
    
    <Msg>
        <Content>Bye bye</Content>
        <Date>2018-02-09+07:00</Date>
        <Format>
            <Color>Black</Color>
            <FontName>TimesNewRoman</FontName>
            <FontSize>14</FontSize>
            <FontStyle>Bold</FontStyle>
        </Format>
    </Msg>
</chatHistory>
